name: Test creating conda environment

on: 
  pull_request:
    branches:
      - main
    paths:
      - environment.yml
  
jobs:
  conda-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Create and Activate Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ex-project-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Test that environment is active
        run: which python
